# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEZZ7JUUJgTYOCTPvGrAq3kCx_L1TDF7
"""

Parte 1: O Algoritmo do Microclima Local
https://colab.research.google.com/notebooks/intro.ipynb#scrollTo=RXBYJGoUh7tB&line=6&uniqifier=1



Parte 2: Navegação e Evacuação Espacial
https://colab.research.google.com/notebooks/intro.ipynb#scrollTo=rTo9h0lxsOZJ&line=238&uniqifier=1



apartamento

3º andar (escada, não tem elevador)



2 quarto (tem 2 trancas, e acessível)

1 sala ( a única entrada e saída)

1 cozinha (aberta com a sala)

1 lavanderia(acesso bloqueado "altura")

1 banheiro

Parte 3: Reflexão Crítica (Além do Código)


**paragrafo 1:**
O que mais me pegou foi ver como a gente tem que "quebrar a cabeça" para traduzir o mundo real em código. Tive que transformar obstáculos físicos, tipo uma porta trancada, em condicionais aninhadas, senão o agente não saberia como reagir. A parte da energia foi legal porque trouxe uma camada de realidade: se o código entrar em loop ou o agente ficar perdido, ele "cansa" e a simulação para. No fim, percebi que programar é basicamente montar um modelo de como a gente toma decisões sob pressão.



**Parágrafo 2:**
O maior desafio pra mim foi "limpar" o que não importava e focar só no que travava o caminho. Foi difícil transformar a casa numa lista de eventos sem deixar o código confuso. Na parte da porta dupla, se eu errasse um if ou a indentação, o agente ficava preso num loop gastando energia à toa. No fim, vi que programar é filtrar o que é essencial pro problema rodar.



**Parágrafo 3:**
Essa atividade me fez ver que programar é tipo montar um plano de segurança. O trajeto parece curto, mas sem a lógica certa pros pré-requisitos (como as chaves) ou o controle da energia, o agente não chega a lugar nenhum. No fim, cada if e else que eu coloquei serviu pra prever um erro e garantir que o caminho fosse o mais eficiente possível, bem parecido com o que a gente faz na vida real quando planeja algo sob pressão.