# -*- coding: utf-8 -*-
"""Sistema De Auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMpCMxvd-fIRDZS6VUDzR62Tcr2id4Kg

# Sistema de Auditoria de Recursos Corporativos
Guilherme Petrucelli Domingos
"""

#Sistema de Auditoria de Recursos Corporativos
import time

# O Decorator (Guilherme)
# Imagine que isso é uma "capa" que envolve a nossa função principal
def auditor(funcao_original):
    def wrapper(*args, **kwargs):
        print("Iniciando a verificacao do orcamento")

        # Pega o horario de inicio
        tempo_inicio = time.time()

        # Executa a funcao de calculo real
        resultado = funcao_original(*args, **kwargs)

        # Pega o horario de termino
        tempo_fim = time.time()

        # Calcula a diferenca
        tempo_gasto = tempo_fim - tempo_inicio

        print("Argumentos usados:", args)
        print("Tempo total de processamento:", tempo_gasto)
        print("Finalizado com sucesso")

        return resultado
    return wrapper

@auditor
def calcular_orcamento(*setores_para_pular, **configuracao_moeda):
    # Nossa estrutura de dados (Dicionario aninhado)
    empresa = {
        "Matriz": {
            "TI": {
                "Infraestrutura": 10000,
                "Software": 20000
            },
            "RH": {
                "Recrutamento": 5000,
                "Folha": 15000
            },
            "Vendas": 30000
        }
    }

    # Funcao de recursao (ela chama ela mesma para entrar nas pastas)
    def percorrer_dicionario(dados_atuais):
        soma = 0

        for nome, valor in dados_atuais.items():
            # Verificamos se o setor deve ser ignorado (*args)
            if nome in setores_para_pular:
                continue

            # Se o valor for outro dicionario, entramos nele (recursao)
            if isinstance(valor, dict):
                soma += percorrer_dicionario(valor)
            else:
                # Se for numero, apenas somamos
                soma += valor
        return soma

    # Inicia o calculo
    total_bruto = percorrer_dicionario(empresa)

    # Faz a conversao se existir no kwargs
    taxa = configuracao_moeda.get("taxa_cambio", 1)
    total_final = total_bruto * taxa

    print("Valor total calculado:", total_final)
    return total_final

# Testando o codigo
if __name__ == "__main__":
    # Exemplo: Ignora o RH e usa taxa de 5.00
    calcular_orcamento("RH", taxa_cambio=5.00)